import Head from "next/head";
import Image from "next/image";
import mypic from "../public/image-product-desktop.jpg";
import { AiOutlineShoppingCart } from "react-icons/ai";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Product Preview Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex items-center justify-center">
      <main className="flex max-w-md mx-auto bg-white rounded-xl overflow-hidden md:max-w-2xl">
        <div className="md:flex">
          <Image
            className="h-48 w-full object-cover md:h-full md:w-64"
            src={mypic}
            alt="Product"
          />
          <div className="px-10 py-10">
            <p className="font-montserrat500 text-transform: uppercase gap-8">
              perfume
            </p>
            <h1 className="font-fraunces text-transform: uppercase text-5xl py-5">
              Gabrielle Essence Eau de parfum
            </h1>
            <p className="text-sm font-montserrat500 py-5">
              A floral, solar and voluptuous interpretation composed by Olivier
              Polge, Perfumer Creator for the House of CHANEL
            </p>
            <div className="flex py-5">
              <div className="font-fraunces text-5xl text-dark_cyan">$149,99</div>
              <div className="line-through">$169,99</div>
            </div>
            <button className="flex items-center justify-center py-2 px-5 bg-dark_cyan text-white gap-8 w-full rounded-lg">
              <AiOutlineShoppingCart /> Add to cart
            </button>
          </div>
        </div>
      </main>
      </div>
    </div>
  );
}
